### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fmay** [tui2tone/vue2-medium-editor#1]
I think the documentation is either wrong or needs an alternative explanation. I am using nuxt and followed the instructions below as per the README

```
import MediumEditor from 'vue2-medium-editor'
Vue.component('medium-editor', MediumEditor)
```

This fails. If you change it to ...
```
import MediumEditor from 'vue2-content-editor'
```
it works. Or maybe I am missing something?

**Comment by tui2tone** [comment]
I didn't update document as well because "vue2-medium-editor" name in npm was taken by other.
Just updated now.
Sorry for that.

**Comment by alisalahio** [comment]
Also, 

`'vue2-medium-editor/src/themes/default.css'`

should be

`'vue2-content-editor/src/themes/default.css'`

in order to work correctly.
